name: Pester

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test-windows-powershell:
    name: powershell
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pester 4
        shell: powershell
        run: |
          Install-Module Pester -RequiredVersion 4.10.1 -Scope CurrentUser -Force -SkipPublisherCheck

      - name: Run tests
        shell: powershell
        run: |
          Import-Module Pester -RequiredVersion 4.10.1
          Invoke-Pester .\Tests -EnableExit

  test-pwsh:
    name: pwsh
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pester 4
        shell: pwsh
        run: |
          Install-Module Pester -RequiredVersion 4.10.1 -Scope CurrentUser -Force -SkipPublisherCheck

      - name: Run tests
        shell: pwsh
        run: |
          Import-Module Pester -RequiredVersion 4.10.1
          Invoke-Pester .\Tests -EnableExit
